import type React from "react"
import {
  Add01Icon,
  Alert01Icon,
  AlignBoxBottomCenterIcon,
  AlignBoxMiddleCenterIcon,
  AlignBoxTopCenterIcon,
  ArrowDown01Icon,
  ArrowExpandDiagonal01Icon,
  ArrowExpandDiagonal02Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  ArrowUpDownIcon,
  BorderAll01Icon,
  BorderBottom01Icon,
  BorderHorizontalIcon,
  BorderInnerIcon,
  BorderLeft01Icon,
  BorderNone01Icon,
  BorderRight01Icon,
  BorderTop01Icon,
  BorderVerticalIcon,
  Calendar03Icon,
  Cancel01Icon,
  CancelCircleIcon,
  CellsIcon,
  CheckIcon,
  CheckmarkCircle01Icon,
  ChevronDown,
  ChevronDownIcon,
  ChevronUp,
  ColumnsThreeCogIcon,
  Comment01Icon,
  Delete02Icon,
  DollarCircleIcon,
  Download01Icon,
  DragDropVerticalIcon,
  DropletOffIcon,
  EditOffIcon,
  File01Icon,
  FileDiffIcon,
  FileImageIcon,
  FilePenIcon,
  FileSpreadsheetIcon,
  FileUploadIcon,
  FilterIcon,
  GalleryThumbnailsIcon,
  Grid2X2XIcon,
  GridViewIcon,
  Heading01Icon,
  HighlighterIcon,
  ImageAdd01Icon,
  ImageCompositionIcon,
  InformationCircleIcon,
  InputNumericIcon,
  InputTextIcon,
  LayoutThreeColumnIcon,
  LeftToRightListBulletIcon,
  LeftToRightListNumberIcon,
  LineIcon,
  Link02Icon,
  Loading03Icon,
  MinusSignCircleIcon,
  Moon02Icon,
  MoreHorizontalIcon,
  PaintBucketIcon,
  ParagraphIcon,
  PathfinderMergeIcon,
  Pen01Icon,
  PercentIcon,
  PlusSignCircleIcon,
  Redo02Icon,
  RotateClockwiseIcon,
  Search01Icon,
  SecondBracketIcon,
  SidebarLeftIcon,
  SourceCodeSquareIcon,
  Sun03Icon,
  Table01Icon,
  TableIcon,
  TableRowsSplitIcon,
  TextAlignCenterIcon,
  TextAlignJustifyLeftIcon,
  TextAlignLeft01Icon,
  TextAlignRight01Icon,
  TextBoldIcon,
  TextCenterlineCenterTopIcon,
  TextCheckIcon,
  TextColorIcon,
  TextItalicIcon,
  TextNumberSignIcon,
  TextStrikethroughIcon,
  TextSubscriptIcon,
  TextSuperscriptIcon,
  TextUnderlineIcon,
  TextWrapIcon,
  Tick02Icon,
  Undo02Icon,
  Upload01Icon,
} from "@hugeicons/core-free-icons"
import { HugeiconsIcon } from "@hugeicons/react"

// The registry source files reference icons through <IconPlaceholder /> with a
// per-library icon name for every icon library the shadcn CLI supports. At
// install time the CLI replaces the placeholder with the consumer's configured
// `iconLibrary` from components.json and strips this import. This component is
// only ever rendered on this docs site, which uses hugeicons.
//
// When a registry component starts using a new icon, add its hugeicons name
// here — the `hugeicons` prop is typed against this registry, so a missing
// entry is a type error.
const hugeicons = {
  Add01Icon,
  Alert01Icon,
  AlignBoxBottomCenterIcon,
  AlignBoxMiddleCenterIcon,
  AlignBoxTopCenterIcon,
  ArrowDown01Icon,
  ArrowExpandDiagonal01Icon,
  ArrowExpandDiagonal02Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  ArrowUpDownIcon,
  BorderAll01Icon,
  BorderBottom01Icon,
  BorderHorizontalIcon,
  BorderInnerIcon,
  BorderLeft01Icon,
  BorderNone01Icon,
  BorderRight01Icon,
  BorderTop01Icon,
  BorderVerticalIcon,
  Calendar03Icon,
  Cancel01Icon,
  CancelCircleIcon,
  CellsIcon,
  CheckIcon,
  CheckmarkCircle01Icon,
  ChevronDown,
  ChevronDownIcon,
  ChevronUp,
  ColumnsThreeCogIcon,
  Comment01Icon,
  Delete02Icon,
  DollarCircleIcon,
  Download01Icon,
  DragDropVerticalIcon,
  DropletOffIcon,
  EditOffIcon,
  File01Icon,
  FileDiffIcon,
  FileImageIcon,
  FilePenIcon,
  FileSpreadsheetIcon,
  FileUploadIcon,
  FilterIcon,
  GalleryThumbnailsIcon,
  Grid2X2XIcon,
  GridViewIcon,
  Heading01Icon,
  HighlighterIcon,
  ImageAdd01Icon,
  ImageCompositionIcon,
  InformationCircleIcon,
  InputNumericIcon,
  InputTextIcon,
  LayoutThreeColumnIcon,
  LeftToRightListBulletIcon,
  LeftToRightListNumberIcon,
  LineIcon,
  Link02Icon,
  Loading03Icon,
  MinusSignCircleIcon,
  Moon02Icon,
  MoreHorizontalIcon,
  PaintBucketIcon,
  ParagraphIcon,
  PathfinderMergeIcon,
  Pen01Icon,
  PercentIcon,
  PlusSignCircleIcon,
  Redo02Icon,
  RotateClockwiseIcon,
  Search01Icon,
  SecondBracketIcon,
  SidebarLeftIcon,
  SourceCodeSquareIcon,
  Sun03Icon,
  Table01Icon,
  TableIcon,
  TableRowsSplitIcon,
  TextAlignCenterIcon,
  TextAlignJustifyLeftIcon,
  TextAlignLeft01Icon,
  TextAlignRight01Icon,
  TextBoldIcon,
  TextCenterlineCenterTopIcon,
  TextCheckIcon,
  TextColorIcon,
  TextItalicIcon,
  TextNumberSignIcon,
  TextStrikethroughIcon,
  TextSubscriptIcon,
  TextSuperscriptIcon,
  TextUnderlineIcon,
  TextWrapIcon,
  Tick02Icon,
  Undo02Icon,
  Upload01Icon,
}

export type IconPlaceholderProps = {
  lucide: string
  tabler: string
  hugeicons: keyof typeof hugeicons
  phosphor: string
  remixicon: string
} & React.ComponentProps<"svg">

export function IconPlaceholder(props: IconPlaceholderProps) {
  const {
    lucide: _lucide,
    tabler: _tabler,
    hugeicons: hugeiconsName,
    phosphor: _phosphor,
    remixicon: _remixicon,
    ...rest
  } = props

  return (
    <HugeiconsIcon
      icon={hugeicons[hugeiconsName]}
      {...(rest as Omit<React.ComponentProps<typeof HugeiconsIcon>, "icon">)}
    />
  )
}
